export interface Author {
  _id: string;
  name: string;
  slug: string;
  bio?: string;
  avatar?: string;
  twitter?: string;
  linkedin?: string;
  expertise: string[];
}

export interface Category {
  _id: string;
  name: string;
  slug: string;
  description?: string;
  color: string;
  icon?: string;
  featuredImage?: string;
  metaTitle?: string;
  metaDescription?: string;
}

export interface Tag {
  _id: string;
  name: string;
  slug: string;
  articleCount: number;
}

export interface ArticleSEO {
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: string;
  canonicalUrl?: string;
  noIndex?: boolean;
}

export interface Article {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  /** Lexical JSON (when written via Payload CMS) or plain HTML string (legacy) */
  content: string | Record<string, unknown>;
  /** HTML version auto-generated by Payload — use this for rendering */
  contentHtml?: string;
  /** Hindi translation fields (optional) */
  title_hi?: string;
  excerpt_hi?: string;
  contentHtml_hi?: string;
  featuredImage?: string;
  category: Category | string;
  tags: string[];
  author: Author | string;
  status: "draft" | "published" | "archived";
  aiSummary?: string;
  readingTime: number;
  views: number;
  commentCount?: number;
  publishedAt: string;
  createdAt: string;
  updatedAt: string;
  seo?: ArticleSEO;
}

export interface ArticlePreview {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  featuredImage?: string;
  category: Pick<Category, "_id" | "name" | "slug" | "color">;
  author: Pick<Author, "_id" | "name" | "slug" | "avatar">;
  tags: string[];
  readingTime: number;
  views: number;
  commentCount?: number;
  publishedAt: string;
}

export interface AITool {
  _id: string;
  name: string;
  slug: string;
  description: string;
  tagline: string;
  category: string;
  pricing: "free" | "freemium" | "paid" | "enterprise";
  pricingDetails?: string;
  features: string[];
  pros: string[];
  cons: string[];
  rating: number;
  website: string;
  logo?: string;
  lastReviewed: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  hasMore: boolean;
}

export interface SearchResult {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  category: string;
  categorySlug: string;
  publishedAt: string;
  featuredImage?: string;
}
